### ISSUE TITLE
NodeGTK bindings

### ISSUE THREAD

**Issue by clayrisser** [clayrisser/react-gtk#1]
I'm first going to build the node bindings in a separate repo using [FFI](https://github.com/node-ffi/node-ffi). Then I'm going to port the node bindings over to React. The reason I'm building my own node bindings is that existing Node bindings are either abandoned or require custom runtime environments.

You can follow and contribute to this project at [node-gtk](https://github.com/jamrizzi/node-gtk3).

**Comment by harisvsulaiman** [comment]
You should take a look at https://github.com/radare/valabind

**Comment by clayrisser** [comment]
Great suggestion, thanks. Would you be interested, or do you know anyone who would be interested in helping me with the bindings?

**Comment by clayrisser** [comment]
I've decided to stick with [FFI](https://github.com/node-ffi/node-ffi).
