### ISSUE TITLE
Port a simple React app as part of documentation

### ISSUE THREAD

**Issue by paulcarroty** [clayrisser/react-gtk#14]
[Tic-tac-toe game](https://reactjs.org/tutorial/tutorial.html#before-we-start-the-tutorial) or something easier, think it will be hyper useful and make this project more interested for developers.

**Comment by clayrisser** [comment]
@paulcarroty any ideas for a good example? I hate todo apps :laughing:

**Comment by paulcarroty** [comment]
[Community examples](https://reactjs.org/community/examples.html) will help. The apps like` HN Client` or `GFonts Space` looks good from everyday using point.
