### ISSUE TITLE
Declare JSX namespace for typescript

### ISSUE THREAD

**Issue by diabolicle** [clayrisser/react-gtk#15]
Hi, I'm trying to run your example project using typescript but I can't seem to get it to work. Can you give me some pointers?

**Comment by diabolicle** [comment]
I got it working by following the instructions here: https://github.com/Microsoft/TypeScript/issues/15449.

**Comment by diabolicle** [comment]
Reopening this because I think this is something that should be included by default.

**Comment by clayrisser** [comment]
@diabolicle awesome. Glad you were able to get it to work. Is there any way I can improve the documentation so others don't make the same mistake?
