### ISSUE TITLE
can't figure out how to use 

### ISSUE THREAD

**Issue by actuallyabhi** [clayrisser/react-gtk#19]
i can't figure out how to use things .there not much docs or references . Can you create a documentation or few sample apps it will be really helpful. or just a list available components and props.

**Comment by clayrisser** [comment]
@mabhishek7081 send me your email address at the link below and I will help you get setup.

https://codejam.ninja/#hire

**Comment by actuallyabhi** [comment]
Thanks a lot jam!

**Comment by actuallyabhi** [comment]
Hiiii @codejamninja . i sent you my details a while ago but i didn't got added somewhere,or any help.
Please look into this!

**Comment by clayrisser** [comment]
@mabhishek7081 I'm sorry I didn't get back to you. I just sent you the invite to slack.

**Comment by actuallyabhi** [comment]
@codejamninja sorry for late reply. I just made slack account and i didn't any invitations. Can you please send invitation once more ?
i am really sorry for the inconvenience.

**Comment by clayrisser** [comment]
@mabhishek7081 sure

**Comment by clayrisser** [comment]
@mabhishek7081 I sent it again
