### ISSUE TITLE
Please stop making React.JS shit

### ISSUE THREAD

**Issue by tripulse** [clayrisser/react-gtk#21]
The worst quality products are made with JavaScript. Don't ruin the GTK like this please!

**Comment by clayrisser** [comment]
Let's use github issues for more objective comments. I can create a subreddit for react-gtk if you would like a spicier conversation.

**Comment by clayrisser** [comment]
I just created the subreddit called [reactgtk](https://www.reddit.com/r/reactgtk) and created a post for this issue.

https://www.reddit.com/r/reactgtk/comments/grndhx/is_binding_javascript_and_react_to_gtk_ruining_gtk/

**Comment by tripulse** [comment]
Well, this was not even a real issue. Just a bad joke.

**Comment by clayrisser** [comment]
@tripulse glad it's just a joke :)

**Comment by Benjozork** [comment]
programmerhumor discord is leaking
