### ISSUE TITLE
How to package as snap or flatpack 

### ISSUE THREAD

**Issue by actuallyabhi** [clayrisser/react-gtk#23]
Hii jam! I just finished my simple app with react-gtk . But i confused how to distribute this. Please help..

**Comment by clayrisser** [comment]
@mabhishek7081 I have not setup packaging yet, but if you are willing to share your code, I would love to help you get it packaged. Is your code open source?

**Comment by actuallyabhi** [comment]
got it ! but while using react-gtk i am facing few issues like
how to use packstart or pack end with Hbox here? i can't figure out it .
 i am really sorry for my stupid questions.'

``` <Box>
        <Button label="Click Me!" borderWidth={50} />
        <SearchBar />
        <HBox />
      </Box>
```

**Comment by clayrisser** [comment]
I’m trying to make the api consistent with the official api. Until I get docs generated, I would recommend looking at the official docs.

The following book I would highly recommend, it covers the entire gtk api.

(This is my copy 😃)

![image](https://user-images.githubusercontent.com/6234038/85197187-efa08a80-b2fc-11ea-8858-8586f7e7df99.jpeg)

Chapter 3 talks about packing.

![image](https://user-images.githubusercontent.com/6234038/85197215-35f5e980-b2fd-11ea-88b8-227562891157.jpeg)

**Comment by clayrisser** [comment]
You can find this book on amazon at this link

https://www.amazon.com/Foundations-Development-Experts-Voice-Source/dp/1590597931

**Comment by clayrisser** [comment]
It’s also quite possible that my current experimental api doesn’t support packing. I’ll make sure it’s supported in my next release .

**Comment by actuallyabhi** [comment]
Got my all queries resolved. Thanks a lot jam :)
I love to contribute in this awesome project.

**Comment by clayrisser** [comment]
You should join the slack channel. I’d love to setup a call so I can go over how it all works. You can join the slack my sending me your email at the following link.

https://codejam.ninja/#hire
